server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: xyz
  flyway:
    enabled: true
    locations: classpath:db/migration
    create-schemas: true
    schemas: car_shop
    default-schema: car_shop
    validate-on-migrate: true
    baseline-on-migrate: false
    clean-disabled: true