server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:carshop-db}:${DB_PORT:5432}/${POSTGRES_DB}

  jpa:
    database-platform: ${JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:none}
    properties:
      hibernate:
        default_schema: ${APP_SCHEMA:car_shop}

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}
    create-schemas: ${FLYWAY_CREATE_SCHEMAS:true}
    schemas: ${APP_SCHEMA:car_shop}
    default-schema: ${APP_SCHEMA:car_shop}
    validate-on-migrate: ${FLYWAY_VALIDATE_ON_MIGRATE:true}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
    clean-disabled: ${FLYWAY_CLEAN_DISABLED:true}
